# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
       lfs: True
    
    # Building as html.
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        
    # Building as a epub.
    - uses: ammaraskar/sphinx-action@master
      with:
        build-command: "make epub"
        docs-folder: "docs/"
        
    # # Grabbing custom dependencies and building as a pdf.
    # - uses: ammaraskar/sphinx-action@master
    #   with:
    #     pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
    #     build-command: "make latexpdf"
    #     docs-folder: "docs/"

    - name: Commit documentation changes
      run: |
        git clone https://github.com/carlogico/Recipes --branch gh-pages --single-branch gh-pages
        cd gh-pages
        git reset --hard  $(git rev-list --max-parents=0 HEAD)
        cd ..
        cp -r docs/build/html/* gh-pages/
        mkdir gh-pages/_downloads
        cp docs/build/epub/Recipes.epub gh-pages/_downloads/Recipes.epub
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation gh-pages" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
